# Generated by Django 4.2.16 on 2024-12-14 20:19

from django.db import migrations, models
import organization.models
import utils.data_validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='background_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=organization.models.organization_background_image_path, validators=[utils.data_validatiors.validate_image_file, utils.data_validatiors.validate_file_size]),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=organization.models.organization_main_image_path, validators=[utils.data_validatiors.validate_image_file, utils.data_validatiors.validate_file_size]),
        ),
    ]
