# Generated by Django 4.2.16 on 2024-12-28 23:39

import django.contrib.postgres.fields
from django.db import migrations, models

import utils.data_validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phoneNumbers',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=20,
                    validators=[utils.data_validatiors.validate_phone_number],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
