# Generated by Django 4.2.16 on 2024-12-15 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
