# Generated by Django 4.2.16 on 2024-12-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='role',
        ),
    ]
