# Generated by Django 4.2.16 on 2024-12-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_remove_organization_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="co_organizer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
