# Generated by Django 4.2.16 on 2024-12-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("distance_details", "0001_initial"),
        ("age_category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agecategory",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="age_categories",
                to="distance_details.distanceevent",
            ),
        ),
    ]
