# Generated by Django 4.2.16 on 2024-11-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distance_details', '0001_initial'),
        ('additional_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalitemevent',
            name='distance',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='additional_options',
                to='distance_details.distanceevent',
            ),
        ),
    ]
