# Generated by Django 4.2.16 on 2024-11-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("additional_items", "0001_initial"),
        ("distance_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalitemevent",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_options",
                to="distance_details.distanceevent",
            ),
        ),
    ]
