# Generated by Django 4.2.16 on 2024-12-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("trail", "Trail"),
                            ("ultramarathon", "Ultramarathon"),
                            ("cycling", "Cycling"),
                            ("online", "Online"),
                            ("walking", "Walking"),
                            ("ocr", "OCR"),
                            ("swimming", "Swimming"),
                            ("triathlon", "Triathlon"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dateFrom", models.DateField()),
                ("dateTo", models.DateField()),
                (
                    "placeRegion",
                    models.CharField(
                        choices=[
                            ("vinnytsia_region", "Vinnytsia oblast"),
                            ("volyn_region", "Volyn oblast"),
                            ("dnipropetrovsk_region", "Dnipropetrovsk oblast"),
                            ("donetsk_region", "Donetsk oblast"),
                            ("zhytomyr_region", "Zhytomyr oblast"),
                            ("zakarpattia_region", "Zakarpattia oblast"),
                            ("zaporizhzhia_region", "Zaporizhzhia oblast"),
                            ("ivano-frankivsk_region", "Ivano-Frankivsk oblast"),
                            ("kyiv_region", "Kyiv oblast"),
                            ("kirovohrad_region", "Kirovohrad oblast"),
                            ("luhansk_region", "Luhansk oblast"),
                            ("lviv_region", "Lviv oblast"),
                            ("mykolaiv_region", "Mykolaiv oblast"),
                            ("odesa_region", "Odesa oblast"),
                            ("poltava_region", "Poltava oblast"),
                            ("rivne_region", "Rivne oblast"),
                            ("sumy_region", "Sumy oblast"),
                            ("ternopil_region", "Ternopil oblast"),
                            ("kharkiv_region", "Kharkiv oblast"),
                            ("kherson_region", "Kherson oblast"),
                            ("khmelnytskyi_region", "Khmelnytskyi oblast"),
                            ("cherkasy_region", "Cherkasy oblast"),
                            ("chernihiv_region", "Chernihiv oblast"),
                            ("chernivtsi_region", "Chernivtsi oblast"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                (
                    "photos",
                    models.ImageField(blank=True, null=True, upload_to="event_photos/"),
                ),
                ("description", models.TextField()),
                ("registrationLink", models.URLField(blank=True, null=True)),
                ("hideParticipants", models.BooleanField(default=False)),
                ("extendedDescription", models.TextField(blank=True, null=True)),
                (
                    "schedulePdf",
                    models.FileField(
                        blank=True, null=True, upload_to="event_schedule/"
                    ),
                ),
                ("coOrganizer", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("unpublished", "Unpublished"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "competitionType",
                    models.ManyToManyField(
                        related_name="event", to="event.competitiontype"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventOrganization",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
