# Generated by Django 4.2.16 on 2024-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="competition_type",
            field=models.ManyToManyField(
                related_name="event", to="event.competitiontype"
            ),
        ),
    ]
