# Generated by Django 4.2.16 on 2024-09-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_organizerevent_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizerevent",
            name="event",
        ),
    ]
