# Generated by Django 4.2.16 on 2024-12-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_competitiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='name',
            field=models.CharField(choices=[('running', 'Running'), ('trail', 'Trail'), ('ultramarathon', 'Ultramarathon'), ('cycling', 'Cycling'), ('online', 'Online'), ('walking', 'Walking'), ('ocr', 'OCR'), ('swimming', 'Swimming'), ('triathlon', 'Triathlon')], max_length=50),
        ),
    ]
