# Generated by Django 4.2.16 on 2024-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('unpublished', 'Unpublished'), ('completed', 'Published')], db_index=True, default='pending', max_length=12),
        ),
    ]
