# Generated by Django 4.2.16 on 2024-12-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="co_organizer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
