# Generated by Django 4.2.16 on 2024-10-11 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_remove_eventregistration_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
