# Generated by Django 4.2.16 on 2024-12-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_event_co_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitiontype",
            name="name",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("trail", "Trail"),
                    ("ultramarathon", "Ultramarathon"),
                    ("cycling", "Cycling"),
                    ("online", "Online"),
                    ("walking", "Walking"),
                    ("ocr", "OCR"),
                    ("swimming", "Swimming"),
                    ("triathlon", "Triathlon"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending approval"),
                    ("unpublished", "Unpublished"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
            ),
        ),
    ]
