# Generated by Django 4.2.16 on 2024-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_organizerevent_phone_number_organizationaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує затвердження'), ('unpublished', 'Не опублікована'), ('published', 'Опублікована')], default='pending', max_length=12),
        ),
    ]
