# Generated by Django 4.2.16 on 2024-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_event_status_alter_organizerevent_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distanceevent",
            name="age_from",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="age_to",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="allow_registration",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("adults", "Дорослі"),
                    ("children", "Діти"),
                    ("men", "Чоловіки"),
                    ("women", "Жінки"),
                    ("disabled", "Учасники з обмеженими можливостями"),
                    ("veterans", "Ветерани"),
                    ("pupils", "Школярі"),
                    ("boys", "Юнаки"),
                    ("juniors", "Юніори"),
                    ("students", "Студенти"),
                    ("teachers", "Викладачі"),
                ],
                default="adults",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="competition_type",
            field=models.CharField(
                choices=[
                    ("running", "Біг"),
                    ("trail", "Трейл"),
                    ("ultramarathon", "Ультрамарафон"),
                    ("cycling", "Велоспорт"),
                    ("online", "Online"),
                    ("walking", "Ходьба"),
                    ("ocr", "OCR"),
                    ("swimming", "Плавання"),
                    ("triathlon", "Тріатлон"),
                ],
                default="running",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="promo_only_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="show_name_on_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="show_start_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="start_number_from",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distanceevent",
            name="start_number_to",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
