# Generated by Django 4.2.16 on 2024-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_organizerevent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerevent',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('moderator', 'Модератор')], default='owner', max_length=10),
        ),
    ]
