# Generated by Django 4.2.16 on 2024-12-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_competitiontype_name_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='name',
            field=models.CharField(
                choices=[
                    ('running', 'Running'),
                    ('trail', 'Trail'),
                    ('ultramarathon', 'Ultramarathon'),
                    ('cycling', 'Cycling'),
                    ('online', 'Online'),
                    ('walking', 'Walking'),
                    ('ocr', 'OCR'),
                    ('swimming', 'Swimming'),
                    ('triathlon', 'Triathlon'),
                ],
                max_length=50,
            ),
        ),
    ]
