# Generated by Django 4.2.16 on 2024-11-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_distanceevent_age_from_distanceevent_age_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='distanceevent',
            name='competition_type',
            field=models.CharField(choices=[('running', 'Running'), ('trail', 'Trail'), ('ultramarathon', 'Ultramarathon'), ('cycling', 'Cycling'), ('online', 'Online'), ('walking', 'Walking'), ('ocr', 'OCR'), ('swimming', 'Swimming'), ('triathlon', 'Triathlon')], default='running', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='competition_type',
            field=models.CharField(choices=[('running', 'Running'), ('trail', 'Trail'), ('ultramarathon', 'Ultramarathon'), ('cycling', 'Cycling'), ('online', 'Online'), ('walking', 'Walking'), ('ocr', 'OCR'), ('swimming', 'Swimming'), ('triathlon', 'Triathlon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('unpublished', 'Unpublished'), ('published', 'Published')], default='pending', max_length=12),
        ),
    ]
