# Generated by Django 4.2.16 on 2024-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_distanceevent_age_from_distanceevent_age_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_region',
            field=models.CharField(
                choices=[
                    ('vinnytsia_region', 'Vinnytsia oblast'),
                    ('volyn_region', 'Volyn oblast'),
                    ('dnipropetrovsk_region', 'Dnipropetrovsk oblast'),
                    ('donetsk_region', 'Donetsk oblast'),
                    ('zhytomyr_region', 'Zhytomyr oblast'),
                    ('zakarpattia_region', 'Zakarpattia oblast'),
                    ('zaporizhzhia_region', 'Zaporizhzhia oblast'),
                    ('ivano-frankivsk_region', 'Ivano-Frankivsk oblast'),
                    ('kyiv_region', 'Kyiv oblast'),
                    ('kirovohrad_region', 'Kirovohrad oblast'),
                    ('luhansk_region', 'Luhansk oblast'),
                    ('lviv_region', 'Lviv oblast'),
                    ('mykolaiv_region', 'Mykolaiv oblast'),
                    ('odesa_region', 'Odesa oblast'),
                    ('poltava_region', 'Poltava oblast'),
                    ('rivne_region', 'Rivne oblast'),
                    ('sumy_region', 'Sumy oblast'),
                    ('ternopil_region', 'Ternopil oblast'),
                    ('kharkiv_region', 'Kharkiv oblast'),
                    ('kherson_region', 'Kherson oblast'),
                    ('khmelnytskyi_region', 'Khmelnytskyi oblast'),
                    ('cherkasy_region', 'Cherkasy oblast'),
                    ('chernihiv_region', 'Chernihiv oblast'),
                    ('chernivtsi_region', 'Chernivtsi oblast'),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='distanceevent',
            name='competition_type',
            field=models.CharField(
                choices=[
                    ('running', 'Running'),
                    ('trail', 'Trail'),
                    ('ultramarathon', 'Ultramarathon'),
                    ('cycling', 'Cycling'),
                    ('online', 'Online'),
                    ('walking', 'Walking'),
                    ('ocr', 'OCR'),
                    ('swimming', 'Swimming'),
                    ('triathlon', 'Triathlon'),
                ],
                default='running',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='competition_type',
            field=models.CharField(
                choices=[
                    ('running', 'Running'),
                    ('trail', 'Trail'),
                    ('ultramarathon', 'Ultramarathon'),
                    ('cycling', 'Cycling'),
                    ('online', 'Online'),
                    ('walking', 'Walking'),
                    ('ocr', 'OCR'),
                    ('swimming', 'Swimming'),
                    ('triathlon', 'Triathlon'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending approval'),
                    ('unpublished', 'Unpublished'),
                    ('published', 'Published'),
                ],
                default='pending',
                max_length=12,
            ),
        ),
    ]
