# Generated by Django 4.2.16 on 2024-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_organizerevent_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaccess',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('organizer', 'Organizer')], max_length=10),
        ),
    ]
