# Generated by Django 4.2.16 on 2024-11-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_competitiontype_remove_event_competition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalitemevent',
            name='distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_options', to='event.distanceevent'),
        ),
    ]
