# Generated by Django 4.2.16 on 2024-11-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_customuser_events_registered'),
        ('event', '0010_additionalitemevent_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
