# Generated by Django 4.2.16 on 2024-11-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_delete_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalitemevent',
            name='event',
        ),
    ]
