# Generated by Django 4.2.16 on 2024-11-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_additionalitemevent_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalitemevent',
            name='event',
        ),
    ]
