# Generated by Django 4.2.16 on 2024-11-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_additionalitemevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitemevent',
            name='item_type',
            field=models.CharField(max_length=50),
        ),
    ]
