# Generated by Django 4.2.16 on 2024-11-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('event', '0014_alter_additionalitemevent_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organization.organizerevent'),
        ),
        migrations.DeleteModel(
            name='OrganizationAccess',
        ),
        migrations.DeleteModel(
            name='OrganizerEvent',
        ),
    ]
