# Generated by Django 4.2.16 on 2024-11-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distance_details', '0001_initial'),
        ('event', '0015_alter_event_organizer_delete_organizationaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitemevent',
            name='distance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_options', to='distance_details.distanceevent'),
        ),
        migrations.DeleteModel(
            name='DistanceEvent',
        ),
    ]
