# Generated by Django 4.2.16 on 2024-11-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_additionalitemevent_distance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalItemEvent',
        ),
    ]
