# Generated by Django 4.2.16 on 2024-11-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("trail", "Trail"),
                            ("ultramarathon", "Ultramarathon"),
                            ("cycling", "Cycling"),
                            ("online", "Online"),
                            ("walking", "Walking"),
                            ("ocr", "OCR"),
                            ("swimming", "Swimming"),
                            ("triathlon", "Triathlon"),
                        ],
                        default="running",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("adults", "Дорослі"),
                            ("children", "Діти"),
                            ("men", "Чоловіки"),
                            ("women", "Жінки"),
                            ("disabled", "Учасники з обмеженими можливостями"),
                            ("veterans", "Ветерани"),
                            ("pupils", "Школярі"),
                            ("boys", "Юнаки"),
                            ("juniors", "Юніори"),
                            ("students", "Студенти"),
                            ("teachers", "Викладачі"),
                        ],
                        default="adults",
                        max_length=50,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "start_number_from",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("start_number_to", models.PositiveIntegerField(blank=True, null=True)),
                ("show_start_number", models.BooleanField(default=False)),
                ("show_name_on_number", models.BooleanField(default=False)),
                ("age_from", models.PositiveIntegerField(blank=True, null=True)),
                ("age_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("promo_only_registration", models.BooleanField(default=False)),
                ("allow_registration", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distances",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
