# Generated by Django 4.2.16 on 2024-12-21 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "competitionType",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("trail", "Trail"),
                            ("ultramarathon", "Ultramarathon"),
                            ("cycling", "Cycling"),
                            ("online", "Online"),
                            ("walking", "Walking"),
                            ("ocr", "OCR"),
                            ("swimming", "Swimming"),
                            ("triathlon", "Triathlon"),
                        ],
                        default="running",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("adults", "Дорослі"),
                            ("children", "Діти"),
                            ("men", "Чоловіки"),
                            ("women", "Жінки"),
                            ("disabled", "Учасники з обмеженими можливостями"),
                            ("veterans", "Ветерани"),
                            ("pupils", "Школярі"),
                            ("boys", "Юнаки"),
                            ("juniors", "Юніори"),
                            ("students", "Студенти"),
                            ("teachers", "Викладачі"),
                        ],
                        default="adults",
                        max_length=50,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("startNumberFrom", models.PositiveIntegerField(blank=True, null=True)),
                ("startNumberTo", models.PositiveIntegerField(blank=True, null=True)),
                ("showStartNumber", models.BooleanField(default=False)),
                ("showNameOnNumber", models.BooleanField(default=False)),
                ("ageFrom", models.PositiveIntegerField(blank=True, null=True)),
                ("ageTo", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("isFree", models.BooleanField(default=False)),
                ("promoOnlyRegistration", models.BooleanField(default=False)),
                ("allowRegistration", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distances",
                        to="event.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostChangeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fromParticipants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fromDate", models.DateField(blank=True, null=True)),
                (
                    "distance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costChangeRules",
                        to="distance_details.distanceevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "distance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriteBy",
                        to="distance_details.distanceevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriteDistances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "distance")},
            },
        ),
    ]
