# Generated by Django 4.2.16 on 2024-12-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteDistance',
        ),
    ]
