# Generated by Django 4.2.16 on 2024-11-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostChangeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_change_rules', to='distance_details.distanceevent')),
            ],
        ),
    ]
