# Generated by Django 4.2.16 on 2024-12-21 17:37

import authentication.managers
import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.data_validatiors


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                (
                    "firstNameEng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lastNameEng", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("dateOfBirth", models.DateField(null=True)),
                (
                    "tShirtSize",
                    models.CharField(
                        choices=[
                            ("XXS", "Very Extra Small"),
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Extra Extra Large"),
                            ("XXXL", "Very Extra Extra Large"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(default="Unknown", max_length=100, null=True),
                ),
                (
                    "city",
                    models.CharField(default="Unknown", max_length=100, null=True),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        max_length=20,
                        null=True,
                        validators=[utils.data_validatiors.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=authentication.models.customer_image_file_path,
                        validators=[
                            utils.data_validatiors.validate_image_file,
                            utils.data_validatiors.validate_file_size,
                        ],
                    ),
                ),
                ("sportsClub", models.CharField(max_length=100, null=True)),
                ("emergencyContactName", models.CharField(max_length=100, null=True)),
                (
                    "emergencyContactPhone",
                    models.CharField(
                        max_length=20,
                        null=True,
                        validators=[utils.data_validatiors.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("organizer", "Organizer"),
                            ("admin", "Administrator"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isStaff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", authentication.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                (
                    "firstNameEng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lastNameEng", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("dateOfBirth", models.DateField(null=True)),
                (
                    "tShirtSize",
                    models.CharField(
                        choices=[
                            ("XXS", "Very Extra Small"),
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Extra Extra Large"),
                            ("XXXL", "Very Extra Extra Large"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(default="Unknown", max_length=100, null=True),
                ),
                (
                    "city",
                    models.CharField(default="Unknown", max_length=100, null=True),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        max_length=20,
                        null=True,
                        validators=[utils.data_validatiors.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=authentication.models.customer_image_file_path,
                        validators=[
                            utils.data_validatiors.validate_image_file,
                            utils.data_validatiors.validate_file_size,
                        ],
                    ),
                ),
                ("sportsClub", models.CharField(max_length=100, null=True)),
                ("emergencyContactName", models.CharField(max_length=100, null=True)),
                (
                    "emergencyContactPhone",
                    models.CharField(
                        max_length=20,
                        null=True,
                        validators=[utils.data_validatiors.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additionalProfiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
