# Generated by Django 4.2.16 on 2024-12-14 21:14

import authentication.models
from django.db import migrations, models
import utils.data_validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=authentication.models.customer_image_file_path, validators=[utils.data_validatiors.validate_image_file, utils.data_validatiors.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=authentication.models.customer_image_file_path, validators=[utils.data_validatiors.validate_image_file, utils.data_validatiors.validate_file_size]),
        ),
    ]
