# Generated by Django 4.2.16 on 2024-12-21 11:06

from django.db import migrations, models
import utils.data_validatiors


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalprofile",
            name="city",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="country",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="emergency_contact_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="emergency_contact_phone",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[utils.data_validatiors.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[utils.data_validatiors.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="sports_club",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="additionalprofile",
            name="t_shirt_size",
            field=models.CharField(
                choices=[
                    ("XXS", "Very Extra Small"),
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Extra Extra Large"),
                    ("XXXL", "Very Extra Extra Large"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="emergency_contact_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="emergency_contact_phone",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[utils.data_validatiors.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[utils.data_validatiors.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sports_club",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="t_shirt_size",
            field=models.CharField(
                choices=[
                    ("XXS", "Very Extra Small"),
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Extra Extra Large"),
                    ("XXXL", "Very Extra Extra Large"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
