# Generated by Django 4.2.16 on 2024-12-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalprofile',
            name='avatar',
        ),
    ]
