# Generated by Django 4.2.16 on 2025-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_additionalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
