# Generated by Django 4.2.16 on 2025-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sportsClub',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
