# Generated by Django 4.2.16 on 2024-10-27 15:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=authentication.models.customer_image_file_path),
        ),
    ]
