# Generated by Django 4.2.16 on 2024-11-03 21:08

from django.db import migrations, models

import utils.data_validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[utils.data_validatiors.validate_phone_number],
                verbose_name='phone number',
            ),
        ),
    ]
