# Generated by Django 4.2.16 on 2024-11-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_additionalprofile_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='events_registered',
        ),
    ]
