# Generated by Django 4.2.16 on 2024-11-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distance_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_options', to='distance_details.distanceevent')),
            ],
        ),
    ]
