# Generated by Django 4.2.16 on 2024-12-21 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("distance_details", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDistanceRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registrationDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("isConfirmed", models.BooleanField(default=False)),
                (
                    "distance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userRegistrations",
                        to="distance_details.distanceevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distanceRegistrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "distance")},
            },
        ),
    ]
