# Generated by Django 4.2.16 on 2024-12-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdistanceregistration_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdistanceregistration',
            name='isConfirmed',
        ),
    ]
