# Generated by Django 4.2.16 on 2024-12-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_items', '0002_initial'),
        ('user', '0004_userdistanceregistration_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistanceregistration',
            name='additionalItems',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='additional_items.additionalitemevent'),
        ),
    ]
