# Generated by Django 4.2.16 on 2025-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_additionalprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdistanceregistration",
            name="startingNumber",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
