# Generated by Django 4.2.16 on 2025-01-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_userdistanceregistration_startingnumber"),
        ("user", "0008_alter_additionalprofile_sportsclub"),
    ]

    operations = []
